# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: windows-latest

variables:
- group: ContainerAppsInfrastructure

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'tfMPN'
    subscriptionId: '2ee2d65e-8a7e-452c-b661-e1891ec4aca9'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-ramesh-nw-dev'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: 'containerApp-azuredeploy.json'
    overrideParameters: >-
          -container_image $(container_image)
          -container_app_name $(container_app_name)
          -environment_name $(environment_name)
          -managed_environment_name $(managed_environment_name)
          -registry_password $(registry_password)
          -registry_username $(registry_username)
    deploymentMode: 'Incremental'

